title : Hugo Zhu
tagline: 树莓派 Golang Rust Raspberry Pi
author :
  name : Hugo Zhu
  email : hugozhu@gmail.com
  github : hugozhu
  twitter : hugozhu
  feedburner : hugozhu

navigation :
  - posts.md  
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - tools.html
  - about.md
  
